#get gene length
library("GenomicFeatures")
library(biomaRt)
listMarts()
mart=useMart('metazoa_mart_18')
listDatasets(mart = mart)
waspTranscriptDb <- makeTranscriptDbFromBiomart(biomart = "metazoa_mart_18", dataset = "nvitripennis_eg_gene")
txsByGene = transcriptsBy(waspTranscriptDb,"gene") # goseq 5.3
lengthData=median(width(txsByGene)) #generate a file with gene ID and their lengths

#get goseq dataframe
#make DEgenes required by pwf function 
Import Dataset ('CussaDESeq_result_GS_S.csv', header=TRUE) # the table was generated by DESeq
genes=as.integer(p.adjust(CussaDESeq_result_GS_S$pval[CussaDESeq_result_GS_S$log2FoldChange!=0],method='BH')<.05) #goseq 6.3 P6
names(genes)=row.names(CussaDESeq_result_GS_S[CussaDESeq_result_GS_S$log2FoldChange!=0,])
table(genes)

#make lengthData format from two collumn downloaded from photozome
Csativus_122_length <- read.delim("~/Csativus_122_length.txt", header=F)
cucucumber_ID<-as.vector(Csativus_122_length[,1])
cucumberlength<-as.numeric(Csativus_122_length[,2])
cucumber_lengthData<-structure(cucumberlength,.Names=cucumber_ID)
pwf<-nullp(genes,bias.data=cucumber_length,plot.fit=TRUE)
