#!/bin/bash
#PBS -q normal
#PBS -J 1-49
#PBS -l select=1:ncpus=24:mem=20G
#PBS -l walltime=5:00:00
#PBS -N bowtie2
#PBS -P Personal

#module load bowtie2/2.29 samtools/1.3

#Ran in interavtive mode:
#bowtie2-build EG5_linked.na pisifera_EG5_ref

# pairwise mapping
# bowtie2 -p 10 -x $PBS_O_WORKDIR/data/oilpalm/reference/pisifera/pisifera_EG5_ref -1 $PBS_O_WORKDIR/data/oilpalm/trimmomatic/${PBS_ARRAY_INDEX}_R1_paired.fq.gz -2  $PBS_O_WORKDIR/data/oilpalm/trimmomatic/${PBS_ARRAY_INDEX}_R2_paired.fq.gz -U $PBS_O_WORKDIR/data/oilpalm/trimmomatic/${PBS_ARRAY_INDEX}_R1_unpaired.fq.gz -U $PBS_O_WORKDIR/data/oilpalm/trimmomatic/${PBS_ARRAY_INDEX}_R2_unpaired.fq.gz -S $PBS_O_WORKDIR/data/oilpalm/bcf/$PBS_ARRAY_INDEX.sam

# single end mapping
file=$(head -n $PBS_ARRAY_INDEX $PBS_O_WORKDIR/data/oilpalm/RADseq/TS3/117-P2/file_list | tail -1)
bowtie2 -p 24 -x $PBS_O_WORKDIR/data/oilpalm/reference/pisifera/pisifera_EG5_ref -U $PBS_O_WORKDIR/data/oilpalm/RADseq/TS3/117-P2/$file -S $PBS_O_WORKDIR/data/oilpalm/RADseq/$file.sam

samtools view -bS $PBS_O_WORKDIR/data/oilpalm/RADseq/$file.sam | samtools sort > $PBS_O_WORKDIR/data/oilpalm/RADseq/$file.sorted.bam

bcftools mpileup -Ou -f $PBS_O_WORKDIR/data/oilpalm/reference/pisifera/EG5_linked.na $PBS_O_WORKDIR/data/oilpalm/RADseq/$file.sorted.bam | bcftools call --threads 24 -mv -Ob -o $PBS_O_WORKDIR/data/oilpalm/RADseq/$file.raw.bcf

bcftools view -i '%QUAL>=30' --threads 24 $PBS_O_WORKDIR/data/oilpalm/RADseq/$file.raw.bcf > $PBS_O_WORKDIR/data/oilpalm/RADseq/$file.Q30.bcf
